

all:
	make -f Makefile.sensor
	make -f Makefile.receiver

install:
	make install -f Makefile.sensor
	make install -f Makefile.receiver

clean:
	make clean -f Makefile.sensor
	make clean -f Makefile.receiver
