CC = g++
DEBUG = -g
CFLAGS = -g -Wall -std=c++11
LFLAGS = -L/usr/local/lib/

INCLUDES = -I/usr/local/include -I.

LIBS = -lzmq -lpthread -lprotobuf

SRCS = simple_receiver.cpp RawDoubleReceiver.cpp double.prot.pb.cc

OBJS = $(SRCS:.cpp=.o)

EXECUTABLE = simple_receiver

all: $(SRCS) $(EXECUTABLE) 

$(EXECUTABLE): $(OBJS)
	$(CC) $(OBJS) -o $(EXECUTABLE) $(LFLAGS) $(LIBS)

.cpp.o:
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	$(RM) *.o *~
#	$(RM) *.o *~ $(EXECUTABLE)
